'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';

export default function SecurityProfilePage() {
  const [setupState, setSetupState] = useState<'idle' | 'scanning' | 'linked'>('idle');
  const [qrCode, setQrCode] = useState('');
  const [secret, setSecret] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleBeginSetup = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/auth/totp/setup', { method: 'POST' });
      const data = await res.json();
      
      if (!res.ok) throw new Error(data.error || 'Failed to initialize setup');
      
      setQrCode(data.qrCodeDataUrl);
      setSecret(data.secret);
      setSetupState('scanning');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleVerify = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/auth/totp/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ secret, token: verificationCode })
      });
      
      const data = await res.json();
      
      if (!res.ok) throw new Error(data.error || 'Invalid verification code');
      
      setSetupState('linked');
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
      <h1 className="font-bold text-botanical-text mb-6 text-4xl md:text-5xl lg:text-6xl">Security & Recovery</h1>
      
      <div className="bg-botanical-surface border border-botanical-border shadow-sm rounded-xl p-6">
        <h2 className="font-semibold text-botanical-text mb-2 text-3xl md:text-4xl">Authenticator App Recovery</h2>
        <p className="text-botanical-muted mb-6 text-base md:text-lg">
          Set up an Authenticator App (like Google Authenticator or Authy) to securely recover your password without relying on email links.
        </p>

        {error && (
          <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-lg mb-6 text-sm">
            {error}
          </div>
        )}

        {setupState === 'idle' && (
          <button
            onClick={handleBeginSetup}
            disabled={loading}
            className="bg-botanical-primary text-white font-semibold py-2 px-6 rounded-lg hover:bg-white hover:text-botanical-primary border border-transparent hover:border-botanical-primary/30 transition-colors disabled:opacity-50"
          >
            {loading ? 'Initializing...' : 'Set Up Authenticator'}
          </button>
        )}

        {setupState === 'scanning' && (
          <div className="space-y-6">
            <div className="bg-white p-4 inline-block rounded-xl">
              <Image src={qrCode} alt="QR Code" width={200} height={200} />
            </div>
            
            <div>
              <p className="text-botanical-text mb-2 text-base md:text-lg">
                1. Scan the QR code with your Authenticator App.
              </p>
              <p className="text-botanical-text mb-4 text-base md:text-lg">
                2. Enter the 6-digit code generated by the app to verify setup.
              </p>
              
              <div className="flex gap-4">
                <input
                  type="text"
                  maxLength={6}
                  placeholder="000000"
                  value={verificationCode}
                  onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
                  className="bg-botanical-surface border border-slate-600 rounded-lg px-4 py-2 text-botanical-text w-32 tracking-widest text-center"
                />
                <button
                  onClick={handleVerify}
                  disabled={loading || verificationCode.length !== 6}
                  className="bg-botanical-primary text-white font-semibold py-2 px-6 rounded-lg hover:bg-white hover:text-botanical-primary border border-transparent hover:border-botanical-primary/30 transition-colors disabled:opacity-50"
                >
                  {loading ? 'Verifying...' : 'Verify & Save'}
                </button>
              </div>
            </div>
          </div>
        )}

        {setupState === 'linked' && (
          <div className="bg-green-500/10 border border-green-500/20 text-green-400 p-4 rounded-lg flex items-center gap-3">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            <span>Authenticator app successfully linked! You can now use it to recover your password.</span>
          </div>
        )}
      </div>
    </div>
  );
}
