CREATE TYPE "Country" AS ENUM ('IN', 'US');

ALTER TABLE "Shop" ADD COLUMN "country" "Country" NOT NULL DEFAULT 'US';
ALTER TABLE "Shop" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Shop" ADD COLUMN "locale" TEXT NOT NULL DEFAULT 'en-US';
ALTER TABLE "Shop" ADD COLUMN "paymentGateway" TEXT NOT NULL DEFAULT 'STRIPE';
