name: Deploy to Vercel

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: vercel/action@v2
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          args: "--prod"
          scope: "${{ github.repository_owner }}"
